ed25519 is not supported in openstack
Used openstack version doesn't support ed25519 keys. We need to make an
exception in public cloud libs.

```

BadRequestException: 400: Client Error for url:
https://engcloud.prv.suse.net:8774/v2.1/aec806fcad544e73bf8c24d6f010afda/os-keypairs,
Keypair data is invalid: failed to generate fingerprint
```