Enable coredns for helm-rmt container image testing
In order to avoid connectivity issues, we need to enable coredns
container in k3s server.

```
Defaulted container "rmt-app" out of: rmt-app, rmt-app-init (init)
error: unable to upgrade connection: container not found ("rmt-app")
```