svirt: Remove <on_reboot> before setting it
Commit f5418ea3149a89a0075deac5c0001bbcfc7512c3 caused a regression on
Xen:

```
error: Failed to define domain from /var/lib/libvirt/images/openQA-SUT-1.xml
error: unsupported configuration: unknown on_reboot action: destroydestroy
```

Proper fix in os-autoinst PR#956.

Fails here: https://openqa.suse.de/tests/1639441
Validation run: http://nilgiri.suse.cz/tests/488