Makefile: Use https protocol
To fix CI error on github change:
./tools/update_spec
git clone git://github.com/os-autoinst/os-autoinst
Cloning into 'os-autoinst'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
make: *** [Makefile:12: prepare] Error 128
Error: Process completed with exit code 2.

Link: https://github.blog/2021-09-01-improving-git-protocol-security-github/

Signed-off-by: Petr Vorel <pvorel@suse.cz>